INSERT INTO burgers (burger_name) VALUES ('Philly Cheese Steak Burger');
INSERT INTO burgers (burger_name) VALUES ('Juicy Lucy');
INSERT INTO burgers (burger_name) VALUES ('Black and Blue');
INSERT INTO burgers (burger_name) VALUES ('Paddy Melt');
INSERT INTO burgers (burger_name) VALUES ('Bacon Egg and Cheese Burger');
INSERT INTO burgers (burger_name) VALUES ('Kobe Burger');
INSERT INTO burgers (burger_name) VALUES ('Waygu Burger');
INSERT INTO burgers (burger_name) VALUES ('50/50 Burger');
INSERT INTO burgers (burger_name) VALUES ('Wahl-Burger');
INSERT INTO burgers (burger_name) VALUES ('Plain Jane');